version: '2'
services:
  api:
    build: .
    container_name: api
    command: bash -c "cd /src/rest && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    links:
      - mongo
    volumes:
      
      - ./adb_test-master:/src

  app:
    build: .
    container_name: app
    command: bash -c "cd /src/app && yarn install && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ./adb_test-master:/src

  mongo:
    build: .
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /home/manu/adb_test-master/db/data/db
    command: /usr/bin/mongod --bind_ip 0.0.0.0

    
